INFO: localdir at /scratch/936624.yma
INFO: your job will run on local system.
                                         clean_title      id  2_way_label
0  my walgreens offbrand mucinex was engraved wit...  awxhir            1
1                this concerned sink with a tiny hat  98pbid            0
2      hackers leak emails from uae ambassador to us  6f2cy5            1
3                           puppy taking in the view  4xypkv            1
4               i found a face in my sheet music too  8gnet9            0
training set:(564000, 3)
validation set:(59342, 3)
testing set:(59319, 3)
Epoch: 0, batch: 35251/1, avg_loss: 0.46755924820899963, loss_per_50: 0.009351184964179993, time:3.15s
Traceback (most recent call last):
  File "/home/yma/thesis_project/FakeNewsDetection_MSc_thesis/main.py", line 61, in <module>
    main(opt)
  File "/home/yma/thesis_project/FakeNewsDetection_MSc_thesis/main.py", line 56, in main
    epoch_time = experiment.train(epoch)
  File "/home/yma/thesis_project/FakeNewsDetection_MSc_thesis/experiments/clip_exper.py", line 53, in train
    for idx, databatch in enumerate(self.train_loader):
  File "/home/yma/miniconda3/envs/NLP_project/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/yma/miniconda3/envs/NLP_project/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/yma/miniconda3/envs/NLP_project/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/yma/miniconda3/envs/NLP_project/lib/python3.9/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yma/miniconda3/envs/NLP_project/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/yma/miniconda3/envs/NLP_project/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yma/miniconda3/envs/NLP_project/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yma/thesis_project/FakeNewsDetection_MSc_thesis/preprocessing/load_data.py", line 106, in __getitem__
    pixel_values = torch.squeeze(inputs["pixel_values"], dim=0) # batch_size,3,224,224
  File "/home/yma/miniconda3/envs/NLP_project/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 237, in __getitem__
    return self.data[item]
KeyError: 'pixel_values'

